evaulate symlinks when comparing $BUILD_DIR against /app
heroku/heroku-buildpack-python pull request #992
Opened 2020-07-08 17:26 UTC by kamaln7

This updates the `$BUILD_DIR` check to evaluate symlinks before comparing to `/app`.

In our build environment we have `/app` symlinked to `/workspace` to accommodate other buildpacks. `$BUILD_DIR` is set to `/workspace`. That causes this buildpack to fail to build because the paths aren't equal so the symlinks are created and in a later step the buildpack tries to install python over the symlink.

```
2020-07-08T15:36:14.47487514Z -----> Installing python-3.6.10
2020-07-08T15:36:14.493172053Z mkdir: cannot create directory â€˜.heroku/pythonâ€™: File exists
2020-07-08T15:36:31.569316508Z  !     Requested runtime (python-3.6.10) is not available for this stack (heroku-18).
2020-07-08T15:36:31.569494894Z  !     Aborting.  More info: 
```

2020-07-08 18:39 UTC, kamaln7 commented
Hmmm I feel like Travis CI is failing because of an unrelated issue?

```
$ bundle exec hatchet ci:setup
/home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.6.0/gems/heroku_hatchet-5.0.3/etc/ci_setup.rb:11:in `fetch': key not found: "HEROKU_API_USER" (KeyError)
	from /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.6.0/gems/heroku_hatchet-5.0.3/etc/ci_setup.rb:11:in `block in <main>'
	from /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.6.0/gems/heroku_hatchet-5.0.3/etc/ci_setup.rb:8:in `open'
	from /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.6.0/gems/heroku_hatchet-5.0.3/etc/ci_setup.rb:8:in `<main>'
/home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.6.0/gems/heroku_hatchet-5.0.3/bin/hatchet:174:in `cmd': Command /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.6.0/gems/heroku_hatchet-5.0.3/etc/ci_setup.rb failed: (RuntimeError)
== Setting Up CI ==
	from /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.6.0/gems/heroku_hatchet-5.0.3/bin/hatchet:35:in `block in <class:HatchetCLI>'
	from /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.6.0/gems/heroku_hatchet-5.0.3/bin/hatchet:179:in `<top (required)>'
	from /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.6.0/bin/hatchet:23:in `load'
	from /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.6.0/bin/hatchet:23:in `<main>'
	from /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.6.0/bin/ruby_executable_hooks:24:in `eval'
	from /home/travis/build/heroku/heroku-buildpack-python/vendor/bundle/ruby/2.6.0/bin/ruby_executable_hooks:24:in `<main>'
The command "bundle exec hatchet ci:setup" exited with 1.
```
`key not found: "HEROKU_API_USER" (KeyError)`
```rb
    file.write <<-EOF
machine git.heroku.com
login #{ENV.fetch('HEROKU_API_USER')}
password #{ENV.fetch('HEROKU_API_KEY')}
EOF
```

2020-07-17 16:31 UTC, edmorley commented
@kamaln7 Hi! Thank you for the PR. The reason Travis is failing is since those credentials are only set for non-fork PRs.

This is on my list to review/trigger a full CI run with creds next week - in the meantime could you rebase on master and fix the merge conflict in `CHANGELOG.MD`? :-)

2020-07-17 22:33 UTC, kamaln7 commented
Thank you, @edmorley! That explains it :)

2020-07-29 12:50 UTC, edmorley commented
@kamaln7 Hi! Just wanted to let you know I haven't forgotten about this, but that #1007 and related changes took up most of my time this week. I have this down on my list to review next week.

2020-08-07 16:10 UTC, edmorley commented
Hmm so the unit tests on Cedar-14, since for Ubuntu 14.04 coreutils doesn't include `realpath` and instead the `realpath` package must be installed explicitly.

Our options are to either update https://github.com/heroku/stack-images to install the `realpath` package (and wait for the next stack image release), or else switch to `readlink -f` instead.

Researching the difference between the two I found:
https://unix.stackexchange.com/questions/136494/whats-the-difference-between-realpath-and-readlink-f

...which muddies the water further by suggesting that `readlink -e` is in fact the more accurate replacement for `realpath`.

2020-08-15 13:19 UTC, kamaln7 commented
Ah thanks @edmorley I admit that I had only tested this on 18.04. I agree that if we should avoid modifying the stack images if we can. `readlink -e` makes sense, if either `/app` or `$BUILD_DIR` don't exist we would want the build to fail because that's a bigger problem there 😅 I can make this change Monday morning if that sounds good to you!

2020-08-20 10:22 UTC, edmorley requested changes
That change sounds good - thank you! Marking this as changes required for now to remove it from my pending reviews list :-)

2020-08-25 09:44 UTC, edmorley commented
I've opened heroku/stack-images/pull/176 to add `realpath` to Cedar-14.

2020-09-09 14:07 UTC, kamaln7 commented
Hi @edmorley very sorry for the delay here. I've just pushed a commit updating the code to use `readlink -e`. https://github.com/heroku/stack-images/pull/176 sounds good 👍🏼

2021-04-08 09:46 UTC, edmorley approved these changes
@kamaln7 Sorry for the delay here. In the meantime, the Cedar-14 stack has been sunset, meaning all buildable stacks now support `realpath`. As such, I've reverted the commit to switch to `readlink`. I've rebased the PR, updated another `BUILD_DIR` comparison to use `realpath` too, and updated the changelog entry for the new style. I've triggered CI (now using Circle) which is passing.

2021-04-08 09:49 UTC, merged

2021-04-08 09:53 UTC, edmorley commented
Meant to say - in the future I hope to remove the `BUILD_DIR` to `/app` comparisons entirely, once the Heroku build system begins building in `/app` (meaning the build time and run time paths no longer differ). Rolling out this change is slow work since there are buildpacks that will break with such a change, so it's required a bunch of outreach.

2021-04-09 21:02 UTC, kamaln7 commented
Hey @edmorley, thanks for the context & the additional fix!